# Generated by Django 3.0.8 on 2020-07-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200728_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberRoom', models.CharField(max_length=10, verbose_name='Номер кабинета')),
                ('titul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Titul')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
    ]
