# Generated by Django 3.0.8 on 2020-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='numberRoom',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер кабинета'),
        ),
    ]
