# Generated by Django 3.0.8 on 2020-07-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20200728_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Titul',
        ),
    ]
