# Generated by Django 3.0.8 on 2020-07-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20200729_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='discription',
            field=models.TextField(default=1, verbose_name='Премечание'),
            preserve_default=False,
        ),
    ]
