# Generated by Django 3.0.8 on 2020-07-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_department_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='position',
        ),
    ]
