# Generated by Django 3.0.8 on 2020-07-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_department_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='depatName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Department', verbose_name='Отдел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Position', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
