# Generated by Django 3.0.8 on 2020-07-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20200726_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='depatName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
