# Generated by Django 3.0.8 on 2020-07-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Organization', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
