# Generated by Django 3.0.8 on 2020-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expendableMaterials', '0002_auto_20200729_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='фото модели'),
            preserve_default=False,
        ),
    ]
