# Generated by Django 3.0.8 on 2020-07-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expendableMaterials', '0003_model_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='word',
            field=models.CharField(default=1, max_length=1, verbose_name='Обозначение'),
            preserve_default=False,
        ),
    ]
