# Generated by Django 3.0.8 on 2020-07-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expendableMaterials', '0004_color_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expendableMaterials.Firm', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='model',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фото модели'),
        ),
    ]
