# Generated by Django 3.0.8 on 2020-07-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expendableMaterials', '0005_auto_20200729_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, verbose_name='Серийный номер')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expendableMaterials.Model', verbose_name='Модель')),
            ],
        ),
    ]
