# Generated by Django 3.0.8 on 2020-07-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expendableMaterials', '0007_model_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='category',
        ),
    ]
