# Generated by Django 3.0.8 on 2020-07-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200729_0753'),
        ('expendableMaterials', '0009_materials_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Расходный материал', 'verbose_name_plural': 'Расходные материалы'},
        ),
        migrations.AddField(
            model_name='materials',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
