# Generated by Django 3.0.8 on 2020-07-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200729_0810'),
        ('expendableMaterials', '0010_auto_20200729_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, verbose_name='Номер')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expendableMaterials.Model', verbose_name='Модель картриджа')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Models', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
            },
        ),
    ]
