# Generated by Django 3.0.8 on 2020-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expendableMaterials', '0012_auto_20200729_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='serialNumber',
            field=models.CharField(max_length=30, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Модель'),
        ),
    ]
