# Generated by Django 3.0.8 on 2020-07-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка статуса'),
        ),
    ]
