# Generated by Django 3.0.8 on 2020-07-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_person_organization'),
        ('act', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fistsName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
