# Generated by Django 3.0.8 on 2020-07-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0002_application_fistsname'),
    ]

    operations = [
        migrations.CreateModel(
            name='act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberAct', models.CharField(max_length=20, verbose_name='Номер акта')),
                ('scan', models.ImageField(blank=True, upload_to='', verbose_name='Скан подписанного акта')),
                ('namberApplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act.Application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
            },
        ),
    ]
