# Generated by Django 3.0.8 on 2020-07-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0004_extradition'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradition',
            name='discription',
            field=models.CharField(default=1, max_length=20, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extradition',
            name='numberAct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act.Act', verbose_name='Акт'),
        ),
    ]
