# Generated by Django 3.0.8 on 2020-07-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0007_auto_20200729_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='numberAct',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер акта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='extradition',
            name='numberAct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act.Act', verbose_name='Акт'),
        ),
    ]
