# Generated by Django 3.0.8 on 2020-07-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200728_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='models',
            name='typeE',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Firms',
        ),
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
