# Generated by Django 3.0.8 on 2020-07-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='typeE',
        ),
    ]
