# Generated by Django 3.0.8 on 2020-07-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_room_titul'),
        ('products', '0008_remove_models_typee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=40, verbose_name='Серийный номер')),
                ('modelProduct', models.CharField(max_length=50, verbose_name='Модель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория оборудования')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Room', verbose_name='Место расположения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
