# Generated by Django 3.0.8 on 2020-07-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200728_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameArm', models.CharField(max_length=100, verbose_name='Имя рабочей станции')),
                ('serialNamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Рабочая станция',
                'verbose_name_plural': 'Рабочие станции',
            },
        ),
    ]
