# Generated by Django 3.0.8 on 2020-07-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200729_0753'),
        ('products', '0011_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
