# Generated by Django 3.0.8 on 2020-07-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ip-адрес'),
        ),
    ]
