# Generated by Django 3.0.8 on 2020-07-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='modelName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Модель'),
        ),
    ]
