# Generated by Django 3.0.8 on 2020-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200729_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='serialNumber',
            field=models.CharField(max_length=40, unique=True, verbose_name='Серийный номер'),
        ),
    ]
